### ISSUE TITLE
欢迎大家提出意见和建议

### ISSUE THREAD

**Issue by kencery** [kencery/Common#1]
# 意见和建议
1. 欢迎大家提出自己独到的意见和建议

**Comment by chucklu** [comment]
https://github.com/kencery/Common/blob/master/common_method/获取电脑信息/GetComputerHelper.cs
GetComputerIp这个方法，HttpContext.Current这里的Current为null

可以考虑下面这个链接的方法？
http://stackoverflow.com/questions/4879837/smart-way-to-get-the-public-internet-ip-address-geo-loc
cs、
string myIp = new WebClient().DownloadString(@"http://icanhazip.com").Trim();
cs、
